### ISSUE TITLE
Include path information in items

### ISSUE THREAD

**Issue by cauebs** [ririsoft/async-walkdir#3]
Walkdir includes the entry's path in a custom error type, because otherwise we just can't really understand the errors, since it's this crate that is issueing the function calls. Possibilities I have thought of so far:

1. Wrap the `std::io::Error` in a custom struct, like `Walkdir::Error`;
2. Make the `Stream`'s `Item` be a struct/tuple containing the path and the `Result`.

I'd be willing to work on this.

**Comment by ririsoft** [comment]
Hello,

I would personally be in favor to stick as close as possible to the original [Walkdir](https://crates.io/crates/walkdir) and thus go for your suggestion 1. What do you think ?
