### ISSUE TITLE
docs: Information on symbolic link following

### ISSUE THREAD

**Issue by zombiepigdragon** [ririsoft/async-walkdir#4]
This is a fairly important point to include in the docs. Given a tree like the following, with `async-walkdir` pointed at the root, what would `async-walkdir` see?

```
/
    a/
        b.txt
        c.txt
    d -> a/
```

(For example: `a/, a/b.txt, a/c.txt, d->a/` or `a/, a/b.txt, a/c.txt, d->a/, d/b.txt, d/c.txt`?)

I could test this myself, but I expected to be able to find it in the docs. Walkdir has [a method](https://docs.rs/walkdir/latest/walkdir/struct.WalkDir.html#method.follow_links) to control this behavior and documents the default. I searched for "link" in the docs, then this crate's `lib.rs`, and I didn't see anything, so if it's documented anywhere it needs to be improved.

**Comment by ririsoft** [comment]
Hello @zombiepigdragon,

Thank you for your comment. I am really sorry about the late reply, I totally missed it.
Would you be open to submit a pull request to either:

- Document the current behavior
- Add the capability to choose the "follow_link" behavior like the original walkdir

?

**Comment by zombiepigdragon** [comment]
Unfortunately, my project using `async-walkdir` was cancelled some time ago. If I do need this crate again, I'll happily submit a PR, but I can't guarantee anything about if or when I will. I'll leave the issue open in case somebody more in need wants to write the test program to find out how this behaves.
