### ISSUE TITLE
document on how to use with tokio runtime

### ISSUE THREAD

**Issue by ibotty** [ririsoft/async-walkdir#8]
Am I supposed to use 
```
block_on(async {
    let mut entries = WalkDir::entries("some/path");
    ...
});
```
even in a `async fn` that is run by tokio's multithreaded runtime?  AFAIU that will setup a separate runtime to run the future.

**Comment by ririsoft** [comment]
Hello @ibotty ,

If you already have an async runtime running you can safely use `Walkdir`, without running another runtime.
This is the whole purpose of this crate.

Does it answer the question ?

**Comment by ibotty** [comment]
Hmm.  You are totally right, it works in my toy example.  I'll figure out, what the problem was in my bigger app.
